services:
  db:
    image: postgres:15.1-alpine
    container_name: pg_emp
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - emp_data:/var/lib/postgresql/data

volumes:
  emp_data: