spring:
  application:
    name: employees-backend
  datasource:
    url: ${DB_HOST_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER_CLASS_NAME}
    connectionTimeout: 60000
    maxLifeTime: 90000
    maximumPoolSize: 20
    idleTimeout: 90000
    minimumIdle: 10
    leakDetectionThreshold: 30000
    connectionTestQuery: SELECT 1
    readOnly: false
    metadata:
      databasePlatform: ${DATABASE_PLATFORM_DIALECT}
      hibernate:
        ddlType: create
        formatSql: false
      showSql: ${LOG_SQL_STATEMENTS}


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.schema: debug
    org.hibernate.orm.boot: debug
    org.hibernate.orm.connections: debug

application:
  jwt:
    secret: ${JWT_SECRET}